### ISSUE TITLE
Sikuli Region Class Supported? 

### ISSUE THREAD

**Issue by lilyzektser** [christianrondeau/SikuliSharp#23]
Hi there,

I need to use the Sikuli Region Class, are there any plans to add this class to the library?

Thanks!
Lily

**Comment by SephirXV** [comment]
<audience changed>
Christian, have you moved to a different visual framework, or moved away
from visual altogether?
I admit Java and Jython is not convenient, I've tried a few others, but
haven't found anything else I could get to work nearly fast enough.

I'd be interested in hearing if you have something working different/better.

On Sep 16, 2018 09:20, "Christian Rondeau" <notifications@github.com> wrote:

Hi @lilyzektser <https://github.com/lilyzektser>, I'm not using Sikuli
anymore so there's no plan for me to add new functionality right now, but
it should be fairly simple to add. If you're open to doing a PR, I can give
you pointers!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/christianrondeau/SikuliSharp/issues/23#issuecomment-421772989>,
or mute the thread

**Comment by christianrondeau** [comment]
@SephirXV long story short, we had a Flash project we needed to have tested, and didn't want to upgrade to support the "new" automated test APIs. But since then, Flash pretty much died, so now that almost everything is using HTML5 (Selenium for automated testing), Sikuli's not useful in our use case. The tech itself is great though :)

**Comment by lilyzektser** [comment]
> Hi @lilyzektser, I'm not using Sikuli anymore so there's no plan for me to add new functionality right now, but it should be fairly simple to add. If you're open to doing a PR, I can give you pointers!

@christianrondeau I would like to try, what are the steps I have to take? I have never done something like this, so I am up for the challenge.

**Comment by christianrondeau** [comment]
@lilyzektser great!

In short the important piece is this line here: https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/SikuliSession.cs#L112

It simply executes `print "SIKULI#: YES" if somecommand(somearguments) else "SIKULI#: NO"`, and then if it prints `SIKULI#: YES` it means the test was positive.

After that, methods like `RightClick` will simply call `RunCommand` with the desired command, e.g. `RunCommand("rightClick", pattern, 0)` (where `pattern`) can be a file (so that it finds it on the screen), or a specific location (e.g. https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/Patterns.cs#L80).

To get started, hardcode your own method with the hardcoded command name that you'd like working in `SikuliSession.cs` that calls `RunCommand`, and then extract whatever parameters you hardcoded as arguments.

There are some things I don't like in how I actually wired this up, like how the number of arguments is fixed... so feel free to just add an overload to `RunCommand` if you find it limiting.

Do a PR and I'll suggest improvements if you're unsure :)

**Comment by tokkyuruessha** [comment]
If you're still interested. I'm working on expanding this project a bit.
Here's a simple Region implementation:
https://github.com/tokkyuruessha/SikuliSharp/commit/26fe3e8fb463757b33ebf2b0a1358afacbe568a9

**Comment by christianrondeau** [comment]
Thanks @tokkyuruessha, Closed by #25
