### ISSUE TITLE
Session.Type misses characters randomly

### ISSUE THREAD

**Issue by apahilaj1029** [christianrondeau/SikuliSharp#5]
Hi Christian,

I've been using your Sikuli wrapper for couple of months now and it's working out pretty well for us.

However, there's this issue that creates a lot of problem here..

We've noticed that randomly Session.Type command will miss entering characters..

Example:  Session.Type("abcdef") would type in "abcf" randomly and would work correctly other times.
I've tried to add a sleep also in between the click and type commands to see if it's related to timing, but it did not help.

Are you aware of this issue ?  I am using SikuliSharp 1.0.3 release.  Thanks much.

**Comment by christianrondeau** [comment]
Hi @apahilaj1029 

Did you test the same script in Sikuli directly?

For the record, I see you have created an issue here: https://answers.launchpad.net/sikuli/+question/186644 though your issue is slightly different... the original issue skips the first letters, yours skips the fourth and fifth...

What SikuliSharp does is simply sending the type command to Sikuli, and waiting for it to complete. There is no SikuliSharp interaction between letters, so if only some of them go through, there's not much that can be solved on the C# side.

To what kind of app are you trying to send the keys? Also, how often does it happen? Half of the time, just a few outliers?

What you could maybe do:

1. Try in Sikuli directly (e.g. using Jython), see if you have the same issue (then, the issue would be on Sikuli)
2. Enter individual letters with a "wait" command, see if that helps (then, diagnose the problem on the app side - maybe it can only buffer a few at a time)
3. Try upgrading to Sikuli 1.1.0 (and SikuliSharp 1.1.0), see if the issue persists

**Comment by apahilaj1029** [comment]
Hi Christian,

Thanks for responding.

I’ve used Sikuli in the past but haven’t seen this issue with it.

This is a Flash application we are trying to automate and this issue happens very frequently (although not 100% of the time) – there’s no rhythm or rhyme to it.

When you say enter individual letters with a wait, are you saying type one character, wait x seconds and then enter another character of the string ?  Example:

Session.Type(“a”);
Thread.Sleep(500);
Session.Type(“b”);
….

We are using Sikuli 1.0.1 currently – is it possible to just upgrade the SikuliSharp to 1.1.0 and leave Sikuli at 1.0.1. just to isolate this issue ?

As an fyi – we are trying a prototype a work around for this issue by simulating a Ctrl C, V commands to copy and paste the entire string buffer to the text elements instead of typing them to see if that helps.  It looks promising so far, but we have yet to roll it out to our entire suite to see how it works.

Thanks,
Arun

**Comment by christianrondeau** [comment]
There's no difference between SikuliSharp 1.0.1 and 1.1.0 *but* the support for Sikuli 1.1.0.

Here's what SikuliSharp does for the `Type` command:

```
var script = string.Format(
  "print \"SIKULI#: YES\" if type(\"{0}\") == 1 else \"SIKULI#: NO\"",
  text
  );

_runtime.Run(script, "SIKULI#: ", 0d);
```

As you can see, it simply runs the `type` command, so if it fails entirely or fails to follow up on the `Type` command, there may be something in SikuliSharp, but since it fails for *some* characters, but continues execution, it cannot be in SikuliSharp. Which is why I suggest trying with Sikuli 1.1.0 (everything should work as-is, as far as I know).

Otherwise, if the copy/paste approach works, good!

**Comment by apahilaj1029** [comment]
Thanks for sharing more information on the Type command…

As of now, our copy/paste approach is working fine for us – no missing of characters -if it starts acting up, I’ll upgrade SikuliSharp and Sikuli to 1.1.0 and give that a try.

Thanks for your time.

Thanks,
Arun

**Comment by christianrondeau** [comment]
Good! I'll close this issue, let me know if you find out more.
