### ISSUE TITLE
SikuliSharp always timeouts on Exists while same image works for other implementation

### ISSUE THREAD

**Issue by Exoow** [christianrondeau/SikuliSharp#8]
So... I was hoping to be able to use SikuliSharp but it fails to find the Google Logo in my test below.
Could be my mistake, but the exact same image and code works for the Sikuli4Net wrapper.

The SikuliSharp code timeouts after 7 seconds (as set in the method call) so everything appears to "work" properly, expect that the image isn't recognized while it should be (as proven by the other wrapper).

SikuliSharp code:

    using (var session = Sikuli.CreateSession())
        {
            var gLogo = Patterns.FromFile(AppDomain.CurrentDomain.BaseDirectory + "\\Resources\\google-logo.PNG");
            var gSearch = Patterns.FromFile(AppDomain.CurrentDomain.BaseDirectory + "\\Resources\\google-search.JPG");
            var xResult = Patterns.FromFile(AppDomain.CurrentDomain.BaseDirectory + "\\Resources\\abc-detail.JPG");

            session.Exists(gLogo, 7);
            session.Wait(gSearch, 7);
            session.Type("abc");
            session.Exists(xResult, 5);
        }

Sikuli4Net code:

            Screen gHome = new Screen();
            Pattern gLogo = new Pattern(AppDomain.CurrentDomain.BaseDirectory + "\\Resources\\google-logo.PNG");
            Pattern gSearch = new Pattern(AppDomain.CurrentDomain.BaseDirectory + "\\Resources\\google-search.JPG");
            Pattern xResult = new Pattern(AppDomain.CurrentDomain.BaseDirectory + "\\Resources\\abc-detail.JPG");

            Assert.IsTrue(gHome.Exists(gLogo, 7));
            gHome.Type(gSearch, "abc");
            Assert.IsTrue(gHome.Exists(xResult, 7));

**Comment by christianrondeau** [comment]
I won't be able to check this out for the next 3-4 weeks... I suggest checking the Sikuli version, otherwise I'd you can,  try debugging from source (the code is in fact fairly simple)  and the Sikuli output should show up (https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/AsyncTwoWayStreamsHandler.cs) 

Sorry i can't be of any more immediate help  but I'm out of the country :P

**Comment by Exoow** [comment]
Hey Christian, thanks for the quick reply.
I've tried another page and I'm getting the same results as before.

Sikuli jar is in an accessible folder (seeing that your code also checks for existing JAR in given PATH).
The error I'm getting is below. **I'm hoping you can help me out in a few weeks!** :-)

```
Result StackTrace:	
at SikuliSharp.AsyncTwoWayStreamsHandler.ReadUntil(Double timeoutInSeconds, String[] expectedStrings)
   at SikuliSharp.SikuliRuntime.Run(String command, String resultPrefix, Double timeoutInSeconds)
   at SikuliSharp.SikuliSession.RunCommand(String command, IPattern pattern, Single timeoutInSeconds)
   at SikuliSharp.SikuliSession.Exists(IPattern pattern, Single timeoutInSeconds)
   at SeleniumFramework.Utils.PageUtils.StillLooksTheSameAs(String path) in C:\TFS\Selenium\SeleniumFramework\Utils\PageUtils.cs:line 131
   at OVVTests.UnitTest1.TestMethod1() in C:\TFS\Selenium\OVVTests\UnitTest1.cs:line 21
Result Message:	
Test method OVVTests.UnitTest1.TestMethod1 threw exception: 
System.TimeoutException: No result in alloted time: 05.0000s
```

**Comment by christianrondeau** [comment]
I'll do what with only a phone!

1. Can you try adding a timeout longer than 5 seconds to Exists;
2. You can compile SikuliSharp in debug mode and check what it logs in VS's Output window


Christian Rondeau On Tue, Sep 13, 2016 at 8:31 AM, Exoow < notifications@github.com [notifications@github.com] > wrote:
Hey Christian, thanks for the quick reply.
I've tried another page and I'm getting the same results as before.

Sikuli jar is in an accessible folder (seeing that your code also checks for existing JAR in given PATH).
The error I'm getting is below. I'm hoping you can help me out in a few weeks! :-)

Result StackTrace:  
at SikuliSharp.AsyncTwoWayStreamsHandler.ReadUntil(Double timeoutInSeconds, String[] expectedStrings)
   at SikuliSharp.SikuliRuntime.Run(String command, String resultPrefix, Double timeoutInSeconds)
   at SikuliSharp.SikuliSession.RunCommand(String command, IPattern pattern, Single timeoutInSeconds)
   at SikuliSharp.SikuliSession.Exists(IPattern pattern, Single timeoutInSeconds)
   at SeleniumFramework.Utils.PageUtils.StillLooksTheSameAs(String path) in C:\TFS\Selenium\SeleniumFramework\Utils\PageUtils.cs:line 131
   at OVVTests.UnitTest1.TestMethod1() in C:\TFS\Selenium\OVVTests\UnitTest1.cs:line 21
Result Message: 
Test method OVVTests.UnitTest1.TestMethod1 threw exception: 
System.TimeoutException: No result in alloted time: 05.0000s

**Comment by Exoow** [comment]
I added the Sikuli source to my project and let it run with the same code.
Is this what you are looking for?

(Also, no problem, it can wait a few weeks!)

```
SIKULI> Hello, this is your interactive Sikuli (rules for interactive Python apply)
SIKULI> use the UP/DOWN arrow keys to walk through the input history
SIKULI> help()<enter> will output some basic Python information
SIKULI> ... use ctrl-d to end the session
print "SIKULI#: YES" if exists(Pattern("C:\\TFS\\dashboardNOK.PNG").similar(0,7), 10) else "SIKULI#: NO"
The thread 0x2688 has exited with code 0 (0x0).
The thread 0x2810 has exited with code 0 (0x0).
The thread 0x4b5c has exited with code 0 (0x0).
The thread 0x20f4 has exited with code 0 (0x0).
The thread 0x2860 has exited with code 0 (0x0).
Exception thrown: 'System.TimeoutException' in SeleniumFramework.dll
```

**Comment by christianrondeau** [comment]
Exactly what is looking for, yes...

Two weird things happening...

1. The timeout exception is a *Selenium* timeout. That might be a clue?
2. Sikuli itself does not output anything after sending the exists request.

My next best idea if increasing the timeout sites not work and the Selenium timeout neither would be to manually launch Sikuli and send the requests as you see them in the console, in interactive mode...

I'm actually looking forward to hearing what the issue was, especially if it could be detected by SikuliSharp in the future!


Christian Rondeau On Tue, Sep 13, 2016 at 12:20 PM, Exoow < notifications@github.com [notifications@github.com] > wrote:
I added the Sikuli source to my project and let it run with the same code.
Is this what you are looking for?

(Also, no problem, it can wait a few weeks!)

SIKULI> Hello, this is your interactive Sikuli (rules for interactive Python apply)
SIKULI> use the UP/DOWN arrow keys to walk through the input history
SIKULI> help()<enter> will output some basic Python information
SIKULI> ... use ctrl-d to end the session
print "SIKULI#: YES" if exists(Pattern("C:\\TFS\\dashboardNOK.PNG").similar(0,7), 10) else "SIKULI#: NO"
The thread 0x2688 has exited with code 0 (0x0).
The thread 0x2810 has exited with code 0 (0x0).
The thread 0x4b5c has exited with code 0 (0x0).
The thread 0x20f4 has exited with code 0 (0x0).
The thread 0x2860 has exited with code 0 (0x0).
Exception thrown: 'System.TimeoutException' in SeleniumFramework.dll

**Comment by Exoow** [comment]
Hey,

the timeout is not Selenium but your Sikuli implementation, on this line:
```
if (!_pendingOutputLines.TryTake(out line, timeout))
    throw new TimeoutException(string.Format(@"No result in alloted time: {0:ss\.ffff}s", timeout));
```
Also, I don't know how to get the interactive mode going, but in the Sikuli-IDE the same image works!
So it's got to be something in your or my code...

Hopefully you can help me when you have computer access again!
Sorry for the trouble!

**Comment by Exoow** [comment]
OK, got interactive mode working...

Error I'm getting is **similar(): expected 1 args; got 2**
I noticed you're passing 0,7 instead of 0.7.
I'll test and keep you notified.

**Comment by christianrondeau** [comment]
Aaah!

In https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/Patterns.cs try converting the time to culture invariant string. Pretty sure that's as simple that!

Let me know!

On Tue, Sep 13, 2016 at 3:29 PM, Exoow < notifications@github.com [notifications@github.com] > wrote:
OK, got interactive mode working...

Error I'm getting is similar(): expected 1 args; got 2
I noticed you're passing 0,7 instead of 0.7.
I'll test and keep you notified.

**Comment by Exoow** [comment]
Yes, the issue has been fixed with the following code.
I'll leave it to you to update, I don't know how to add changes via Github.
```

using System.Globalization;

public string ToSikuliScript()
{
	return string.Format(NumberFormatInfo.InvariantInfo, "Pattern(\"{0}\").similar({1})", _path.Replace(@"\", @"\\"), _similarity);
}
```

**Comment by christianrondeau** [comment]
Thanks for the PR, I'll merge that and deploy a new NuGet version as soon as I can!

Glad you could figure out a solution!


Christian Rondeau On Wed, Sep 14, 2016 at 7:47 AM, Exoow < notifications@github.com [notifications@github.com] > wrote:
Yes, the issue has been fixed with the following code.
I'll leave it to you to update, I don't know how to add changes via Github.


using System.Globalization;

public string ToSikuliScript()
{
    return string.Format(NumberFormatInfo.InvariantInfo, "Pattern(\"{0}\").similar({1})", _path.Replace(@"\", @"\\"), _similarity);
}
